CREATE TABLE pedido (
  pedidoid BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   codigo_pedido UUID,
   quantidade INT NOT NULL,
   preco DECIMAL NOT NULL,
   cliente_clienteid BIGINT,
   produto_produtoid BIGINT,
   CONSTRAINT pk_pedido PRIMARY KEY (pedidoid)
);

ALTER TABLE pedido ADD CONSTRAINT FK_PEDIDO_ON_CLIENTE_CLIENTEID FOREIGN KEY (cliente_clienteid) REFERENCES cliente (clienteid);

ALTER TABLE pedido ADD CONSTRAINT FK_PEDIDO_ON_PRODUTO_PRODUTOID FOREIGN KEY (produto_produtoid) REFERENCES produto (produtoid);